# Generated by Django 2.2.13 on 2020-09-22 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20200923_0110'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment',
            new_name='commentsa',
        ),
        migrations.AlterField(
            model_name='comment',
            name='listid',
            field=models.IntegerField(default=0),
        ),
    ]
