# Generated by Django 2.2.13 on 2020-09-28 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20200923_0111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='commentsa',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
    ]
