# Generated by Django 2.2.13 on 2020-09-28 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auto_20200928_1540'),
    ]

    operations = [
        migrations.CreateModel(
            name='Closedbid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=64)),
                ('winner', models.CharField(max_length=64)),
                ('listid', models.IntegerField()),
                ('bidprice', models.IntegerField()),
            ],
        ),
    ]
