# Generated by Django 2.2.13 on 2020-09-28 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_closedbid'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Closedbid',
            new_name='Closebid',
        ),
    ]
