# Generated by Django 2.2.13 on 2020-09-28 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auto_20200929_0023'),
    ]

    operations = [
        migrations.RenameField(
            model_name='closebid',
            old_name='winner',
            new_name='title',
        ),
    ]
