# Generated by Django 2.2.13 on 2020-09-28 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_auto_20200929_0045'),
    ]

    operations = [
        migrations.AddField(
            model_name='closebid',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
