# Generated by Django 2.2.13 on 2020-11-15 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_auction_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='category',
            field=models.CharField(choices=[('BK', 'BOOK'), ('EL', 'Electronics'), ('Ty', 'Toys'), ('SR', 'Shoes'), ('ot', 'other')], default='BK', max_length=60),
        ),
    ]
