# Generated by Django 2.2.13 on 2020-11-16 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_auto_20201116_0211'),
    ]

    operations = [
        migrations.AddField(
            model_name='closebid',
            name='image1',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='auction',
            name='category',
            field=models.CharField(choices=[('Book', 'BOOK'), ('Electronics', 'Electronics'), ('Toys', 'Toys'), ('Shoes', 'Shoes'), ('other', 'other')], default='Book', max_length=60),
        ),
    ]
